/// <reference types="cypress" /

describe('', () => {
  it('should login', () => {
    cy.visit('/')
    cy.get('[formcontrolname="email"]').type('testemail2@test.ts')
    cy.get('[formcontrolname="password"]').type('testpassword')
    cy.get('ion-button[data-cy="loginButton"]').shadow().find('button').click({force: true})
  })
  it('should sign an order', () => {
    cy.visit('/')
    cy.get('[formcontrolname="email"]').type('testemail2@test.ts')
    cy.get('[formcontrolname="password"]').type('testpassword')
    cy.get('ion-button[data-cy="loginButton"]').shadow().find('button').click({force: true})
    cy.get('ion-menu-button').shadow().find('button').click({force: true})
    cy.get('ion-item[routerlink="/order-list"]').click({force: true})
    cy.wait(300)
    cy.get('ion-menu-toggle').click({multiple: true})
    cy.wait(30000)
    cy.get('ion-card').first().click({multiple: true, force: true})
    cy.get('app-sign-picker').find('ion-button').click({force: true, multiple: true})
    cy.get('canvas').should('be.visible')

  })
  it('should show route', () => {
    cy.visit('/')
    cy.get('[formcontrolname="email"]').type('testemail2@test.ts')
    cy.get('[formcontrolname="password"]').type('testpassword')
    cy.get('ion-button[data-cy="loginButton"]').shadow().find('button').click({force: true})
    cy.get('ion-menu-button').shadow().find('button').click({force: true})
    cy.get('ion-item[routerlink="/order-list"]').click({force: true})
    cy.wait(300)
    cy.get('ion-menu-toggle').click({multiple: true})
    cy.wait(30000)
    cy.get('ion-card').first().click({multiple: true, force: true})
    cy.get('app-map-opener').find('ion-button').click({multiple: true, force: true})
    cy.get('button').first().click()
  })

  it('should toggle dark mode', () => {
    cy.visit('/')
    cy.get('[formcontrolname="email"]').type('testemail2@test.ts')
    cy.get('[formcontrolname="password"]').type('testpassword')
    cy.get('ion-button[data-cy="loginButton"]').shadow().find('button').click({force: true})
    cy.get('ion-menu-button').shadow().find('button').click({force: true})
    cy.get('ion-item[routerlink="/settings"]').click({force: true})
    cy.wait(300)
    cy.get('ion-menu-toggle').click({multiple: true})
    cy.get('ion-toggle').click({multiple: true, force: true})
    cy.get('body').should('have.class', 'dark')
  })

  it('should change language', () => {
    cy.visit('/')
    cy.get('[formcontrolname="email"]').type('testemail2@test.ts')
    cy.get('[formcontrolname="password"]').type('testpassword')
    cy.get('ion-button[data-cy="loginButton"]').shadow().find('button').click({force: true})
    cy.get('ion-menu-button').shadow().find('button').click({force: true})
    cy.get('ion-item[routerlink="/settings"]').click({force: true})
    cy.wait(300)
    cy.get('ion-menu-toggle').click({multiple: true})
    cy.get('ion-select').first().shadow().find('button').click({force:true})
    cy.get('button').eq(1).click({multiple: true, force:true})
    cy.contains('OK').click({multiple:true, force:true})
    cy.contains('Magyar').should('contain', 'Magyar')

  })
  it('should reject order', ()=>{
    cy.visit('/')
    cy.get('[formcontrolname="email"]').type('testemail2@test.ts')
    cy.get('[formcontrolname="password"]').type('testpassword')
    cy.get('ion-button[data-cy="loginButton"]').shadow().find('button').click({force: true})
    cy.get('ion-menu-button').shadow().find('button').click({force: true})
    cy.get('ion-item[routerlink="/order-list"]').click({force: true})
    cy.wait(300)
    cy.get('ion-menu-toggle').click({multiple: true})
    cy.wait(30000)
    cy.get('ion-card').first().click({multiple: true, force: true})
    cy.wait(100)
    cy.get('[data-cy="reject-button"]').click({ multiple: true ,force:true})
    cy.wait(100)
    cy.get('app-order-popover').contains('Elutasít').click({force: true, multiple: true})
    cy.wait(100)
    cy.contains('Senki nem jött ki').click({multiple: true ,force:true})
  })
})
